### ISSUE TITLE
-sourcelinePC fails in master

### ISSUE THREAD

**Issue by necipfazil** [appleseedlab/superc#166]
```$ java superc.SuperC -sourcelinePC /dev/null /dev/null
SuperC, v. 2.4.0, (C) 2009-2012 New York University
Portions Copyright (c) 1989, 1990 James A. Roskind
Processing /dev/null ...
java.lang.IncompatibleClassChangeError: Found interface superc.core.PresenceConditionManager$PresenceCondition, but class was expected
	at superc.core.MacroTable._define(MacroTable.java:203)
	at superc.core.MacroTable.define(MacroTable.java:193)
	at superc.core.Preprocessor.defineDirective(Preprocessor.java:2107)
	at superc.core.Preprocessor.evaluateDirective(Preprocessor.java:924)
	at superc.core.Preprocessor.__next(Preprocessor.java:426)
	at superc.core.Preprocessor.next(Preprocessor.java:371)
	at superc.core.Preprocessor.next(Preprocessor.java:65)
	at superc.SuperC.parse(SuperC.java:878)
	at xtc.util.Tool.run(Tool.java:502)
	at superc.SuperC.main(SuperC.java:2012)
1 error
```

This works in sourceline_pc branch.  The error is potentially due to the recent merge on master.

**Comment by necipfazil** [comment]
Building a clean superc fixed the issue (`make clean; make configure; make`)
